[package]
name = "rota-cli"
version.workspace = true
edition = "2021"

[[bin]]
name = "rota"
path = "src/main.rs"

[dependencies]
clap = "4.5.4"
crossbeam = { version = "0.8.4", features = [
    "crossbeam-channel",
    "crossbeam-queue",
] }
rota = { path = "../lib" }
